## Упражнения по библиотеке Numpy

import numpy as np

In [241]:
!pip install numpy


[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [242]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [243]:
# your code
m = np.arange(15)
m[(3 < m) & (m <= 8)] *= -1

In [244]:
print(m)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


**2.** Заменить максимальный элемент случайного массива на 0

In [245]:
# your code
m = np.random.random(7)
m[m.argmax()] = 0
print(m)

[0.         0.7371342  0.30368688 0.22672836 0.32810555 0.44420139
 0.65308583]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [246]:
# your code
def block(arrays):
    arrays = [np.asarray(x) for x in arrays]
    forming = map(len, arrays)

    fx = np.indices(forming, dtype=int)
    fx = fx.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        fx[:, n] = arrays[n][fx[:, n]]

    return fx

print(block(([1, 2], [3, 4], [5, 6, 7])))

[[1 3 5]
 [1 3 6]
 [1 3 7]
 [1 4 5]
 [1 4 6]
 [1 4 7]
 [2 3 5]
 [2 3 6]
 [2 3 7]
 [2 4 5]
 [2 4 6]
 [2 4 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [247]:
# your code
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[...,np.newaxis,np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 6 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [248]:
# your code
D = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(D[:,1:] == D[:,:-1], axis=1)
I = D[~E]
print(D)
print(I)

[[3 1 0]
 [1 0 0]
 [0 1 3]
 [1 2 0]
 [4 4 0]
 [4 4 4]
 [2 0 4]
 [0 0 4]
 [2 1 1]
 [4 4 1]]
[[3 1 0]
 [1 0 0]
 [0 1 3]
 [1 2 0]
 [4 4 0]
 [2 0 4]
 [0 0 4]
 [2 1 1]
 [4 4 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [249]:
# your code
a = np.array([
    [1, 2, 3],
    [1, 2, 3]
])


In [250]:

np.unique(a, axis=0)

array([[1, 2, 3]])

In [251]:
# если надо сохранить порядок строк
a = [[1, 2, 3],
    [4, 5, 6],
    [5, 5, 7],
    [1, 2, 3],
    [3, 2, 1]]


In [252]:
b = np.array(a)

In [253]:
u,idx = np.unique(b, axis=0, return_index=True)
res = u[idx.argsort()]

In [254]:
res

array([[1, 2, 3],
       [4, 5, 6],
       [5, 5, 7],
       [3, 2, 1]])

______
______

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

In [255]:
# your code
x = np.array([[1, 0, 1],[2, 0, 2], [3, 0, 3], [4, 4, 4]])
my_prod = np.prod(np.diag(x)[np.diag(x)!=0])
my_prod

3

In [256]:
# конспект
# from random import randint
#matrix = [[randint(0, 10) for y in range(10)] for x in range(10)]
#m =1
#for i in range(10):
    #if matrix[i][i]:
       # m *= matrix[i][i]
#print(m)


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [257]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

equal = np.any([x ,y])
equal
#if np.array_equal(x ,y): 
    # print("x == y")
#print((x == y).all())



True

In [258]:
# конспект
#x = np.array([1, 2, 2, 4])
#y = np.array([4, 2, 1, 2])
#g = np.allclose(x,y)
#print(g)

In [259]:
# конспект
# hj = np.all(x == y)
#hj
#np.all(a == a[0])

In [260]:
#конспект
#eq = np.isclose(x,y)
#eq

In [261]:
#конспект
# np.array_equal(x,y)

In [262]:
# конспект
# result5 = np.array(set(x).intersection(y))
#result5

In [263]:
# конспект
# c = np.intersect1d(x, y)
#c

In [264]:
# конспект
# k = np.array_equiv(x, y)
# k

In [265]:
# конспект
# h = np.array_equal(x,y)
# h

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [266]:
a = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = a==0
a[1:][zero[:-1]].max()

5

In [267]:
# конспект
#print(np.max(np.take(a, np.where(a[1:] == 0))))
#ответ 7

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [268]:
def encode(a):
    ia = np.asarray(a)
    n = len(ia)
    if n == 0: 
        return (None, None)
    else:
        y = np.array(ia[1:] != ia[:-1])
        i = np.append(np.where(y), n - 1)
        z = np.diff(np.append(-1, i))
        return(ia[i], z)

A = np.array([2, 2, 2, 3, 3, 3, 5])
print(encode(A))

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [269]:
!pip install scipy


[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [270]:
import scipy

In [271]:
point7 = np.random.randint(5, size=(5, 3))
point8 = np.random.randint(5, size=(4, 3))

dist = scipy.spatial.distance.cdist(point7,point8)
dist

array([[5.        , 2.44948974, 5.        , 2.23606798],
       [5.        , 3.74165739, 5.        , 3.60555128],
       [4.47213595, 2.23606798, 4.47213595, 2.44948974],
       [3.60555128, 1.41421356, 3.60555128, 2.23606798],
       [2.82842712, 1.        , 2.82842712, 2.44948974]])

In [272]:
%timeit dist = scipy.spatial.distance.cdist(point7,point8)

3.99 µs ± 54.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [273]:

def dist_pairwise(X, Y):
    P = np.add.outer(np.sum(X**2, axis=1), np.sum(Y**2, axis=1))
    N = np.dot(X, Y.T)
    return np.sqrt(P - 2*N)

X = np.random.randint(5, size=(5, 3))
Y = np.random.randint(5, size=(4, 3))


dists = dist_pairwise(X, Y)
dists

#dists.shape


array([[5.38516481, 4.35889894, 3.        , 3.16227766],
       [1.41421356, 1.41421356, 3.74165739, 3.        ],
       [3.16227766, 2.82842712, 3.16227766, 3.        ],
       [3.16227766, 2.44948974, 2.44948974, 2.23606798],
       [4.12310563, 4.58257569, 4.12310563, 3.16227766]])

In [274]:
%timeit dists = dist_pairwise(X, Y)

17 µs ± 3.01 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [275]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [276]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [277]:
portion = 60


average = np.mean (calorie_stats)
average

106.88311688311688

In [278]:
average_calories = np.mean (calorie_stats) - portion
average_calories

46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [279]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [280]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [281]:
first = np.percentile(calorie_stats_sorted, 100)
first
#nth_percentile =

160.0

In [282]:
second = np.percentile(calorie_stats_sorted, 70)
second

110.0

In [283]:
third = np.percentile(calorie_stats_sorted, 50)
third

110.0

In [284]:
fouth = np.percentile(calorie_stats_sorted, 30)
fouth

100.0

In [285]:
fifth = np.percentile(calorie_stats_sorted, 10)
fifth

90.0

In [286]:
nth_percentile = np.percentile(calorie_stats_sorted, 3.3)
nth_percentile

60.16

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [287]:
count_nonzero_all = np.count_nonzero (calorie_stats)

In [288]:
count_nonzero_moresixty = np.count_nonzero (calorie_stats > 60)

In [289]:
more_calories = (count_nonzero_moresixty/count_nonzero_all)*100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [290]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

In [291]:
#стандартное отклонение 19,36 - это величина вариации в наборе данных calorie_stats относительно его среднего арифм. значения (mean): насколько далеко от 
# среднего арифметического находятся точки данных. Его также можно назвать мерой центральной тенденции: чем меньше стандартное отклонение, тем более «сгруппированы» данные вокруг центра (среднего). 
# Чем отклонение больше, тем больше разброс значений

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [292]:
# Хлопья являются конкурентоспособным продуктом, способным удовлетворить потребности потребителей, что потверждается расчетом статистических показателей. Так, основной показатель продукта,
# калорийность, значительно ниже аналогичного показателя конкурентов, почти в 2 раза. После сортировки данных и проведения расчетов видно, что медиана и среднее значение не равны. 
# Медианное значение больше и оно является наиболее корректным показателем набора данных в данном случае. 
# Статистические показатели (среднее и медиана) показывают, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.
# Калорийность отклоняется от среднего примерно на 19,36.
# Расчет процентиля также показывает, что почти у всех конкурентов (около 97%) количество калорий выше